- assets/add/@web-root/sites/default/local.settings.php.twig
- assets/merge/.env.twig
- assets/merge/.gitignore.twig
- assets/replace/Makefile
- assets/replace/manifests/local/docker-compose.yml.twig
- composer.json
- questions.json
Small improvements and fixes to the current IDP:
* The change to the virtual hosts generation will deprecate the usage of different local domains as opposed to subdomains (e.g. `test.example-sw-project.localdev.iqual.ch` vs. `test.localdev.iqual.ch`).
> #US-1128: Minor improvements and fixes

- assets/replace/.vscode/settings.json.twig
- assets/replace/README.md.twig
- assets/replace/manifests/local/docker-compose.yml.twig
If the code name (`name` variable) does not adhere to the default project naming scheme (`CODE_NAME-sw-project`) then it can be overridden with the `project_name` variable. However this is not yet the case in every asset template (e.g. `VIRTUAL_HOST` in `docker-compose.yml` file).
* The goal is to deprecate this feature eventually. Projects should always be adhering to the naming scheme.
> Fix project name override

- composer.json
Currently the asset package supports any version of the `project-scaffold` composer plugin. It should only support the stable version `^1.0`.
> Add version constraint to `project-scaffold`

- assets/replace/Makefile
> Added config directory creation in `new` target

- assets/replace/Makefile
> Improv prompt in `delete-local` target

- assets/replace/Makefile
> Fix docker compose v2 support

- assets/replace/.vscode/launch.json
- assets/replace/.vscode/tasks.json
- assets/replace/Makefile
- docs/commands.md
- docs/drupal-development.md
* XDebug is set to `trigger` by default
* The Drupal image has a new `enable_xdebug` and `disable_xdebug` script.
* This PR thus adds support for just in time debugging:
* Adds a new `xdebug` and `xdebug-disable` make target
* Adds an enable & disable xdebug task in `tasks.json` calling `make`.
* Adds a `preLaunchTask` and `postDebugTask` to the XDebug VS Code extension
This way XDebug gets “all the way” enabled when pressing F5 in VS Code and will also be disabled afterwards. By default XDebug will still be in `trigger` mode as a fallback.
> #US-1145: Optimize XDebug integration

- assets/replace/.github/actions/install-local/action.yml.twig
- assets/replace/.github/workflows/update.yml.twig
- assets/replace/.github/workflows/visual-regression-testing.yml.twig
> #US-1333: Upgrade deprecated github actions

- assets/replace/.github/workflows/update.yml.twig
- assets/replace/.github/workflows/upgrade.yml.twig
* Remove `reviewers` option from PR creation workflow action
* Applies to `upgrade.yml` and `update.yml`
> #US-1382: Fix upgrade workflow reviewer issue

- assets/replace/.github/actions/upgrade/upgrade.sh
* The data has to in escaped double quotes when using whitespaces, e.g. `"data": ["drupal/example", "\"example with whitespace\""]`
> #US-1464: Fix patch operations in upgrade workflow

- assets/merge/.platform.app.yaml.twig
- docs/deployment.md
Currently the location rule in the `.platform.app.yaml` is disallowing file system assets and passes the `robots.txt` to PHP which doesn’t find it ([here](https://github.com/iqual-ch/drupal-platform/blob/5f181922b7cd1964ed0dc7c065ebbab8c78e83f4/assets/merge/.platform.app.yaml.twig#L140-L143)). The `passthru` is however redundant. This should be changed to `allow: true` and the `passthru` removed.
The implication is: For a multi-domain setup it is now required that the `robots.txt` file is removed from the repository and the drupal scaffold file mapping is disabled in the`extra.drupal-scaffold.file-mapping` composer config by setting it to `"[web-root]/robots.txt": false`.
> #US-1896: Fix `robots.txt` handling on multi-domain for Platform.sh

- assets/replace/@web-root/sites/default/settings.platformsh.php.twig
The `system.logging` `error_level` is set to `verbose` on production. It should be `hide`. This is due to the drupal platform relying on `onProduction()` by Platform.sh config reader [here](https://github.com/iqual-ch/drupal-platform/blob/v1.6.1/assets/replace/%40web-root/sites/default/settings.platformsh.php.twig#L41). However that expects `master` instead of `main` [here](https://github.com/platformsh/config-reader-php/blob/2.4.1/src/Config.php#L440).
> #PF-419: Fix `error_level` for production environment on Platform.sh

- assets/merge/.platform.app.yaml.twig
Currently `avif` and `webp` files are not allowed outside of the `/sites/default/files` files route. To support these modern image formats in modules or themes, it should be added to the allowed static files list. See the [official Drupal 10 template from Platform.sh](https://github.com/platformsh-templates/drupal10/blob/master/.platform.app.yaml#L118).
> #PF-470: Fix `avif` and `webp` static file support

- assets/replace/.vscode/settings.json.twig
The file associations for Drupal-specific PHP files are missing from the VS Code settings (e.g. `.module`, or `.theme`).
> #PF-471: Add missing Drupal files associations

- assets/replace/@web-root/sites/default/settings.platformsh.php.twig
It is not be possible to access multi-domain sites on non-prod when on the `main` branch using Platform.sh due to the fix in #32.
> #PF-423: Fix multi-domain for non-prod env on `main`

- assets/replace/@app-root/resources/build.sh.twig
- assets/replace/@app-root/resources/deploy.sh.twig
The `fontyourface` folder in the repository is in the `publis/sites/default/files` mount. Files present during the build phase (including the ones in the repository) can’t be deployed to mounted folders if they’re not empty. This has already been mitigated for the SCSS compilation of `iq_custom`. The same, or a similar, approach should be implemented for these kind of asset files.
> #PF-422: Fix `fontyourface` support

- assets/replace/@web-root/sites/default/settings.platformsh.php.twig
The rotues should only be loaded when in a Platform.sh runtime. Currently it throws an error locally:
```
No routes are defined.  Are you sure you are running on Platform.sh?  
```
> #PF-423: Fix multi-domain routes for local

- assets/replace/.github/workflows/testing.yml.twig
Currently testing workflows will only run when `opening` or `reopening` pull requests. Instead of forcing developers to re-open PRs, add the `ready_for_review` trigger so it is possible to put PRs into draft and then set them to ready for review.
> #PF-467: Added `ready_for_review` trigger on `pull_request`

- assets/replace/@app-root/resources/deploy.sh.twig
- docs/deployment.md
Currently Drupal is always built and deployed automatically by default on Platform.sh. This can lead to issues when restoring backups or for automation where you do not want to run any database hooks (config import or update hooks) or change any assets.
* When only disabling `drush deploy` then themes or assets might still be overwritten from the build phase but not compiled (e.g. `css` in `iq_barrio`.
* When disabling the deployment script altogether custom module and theme code might not be up to date.
> #PF-466: Add option for no-remote deployment for Platform.sh

- assets/replace/.github/workflows/phpcs.yml.twig
- assets/replace/@app-root/resources/utility.mk
* When there is any warning from `phpcs` it will exit with a non-zero code.
* Also `cs2pr` will exit with a non-zero code on a warning.
* `.css` files are being sniffed, even though they are compiled.
> #PF-505: Graceful `phpcs` warnings and disable `css` sniffing

- assets/replace/.github/actions/install-local/action.yml.twig
- assets/replace/.github/workflows/phpunit-functional-testing.yml.twig
- assets/replace/.github/workflows/update.yml.twig
- assets/replace/.github/workflows/upgrade.yml.twig
Some GitHub Actions workflows are outdated and need updating. [Node v16 will also be deprecated](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/).
> #PF-488: Update GitHub Actions workflows
